package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Main page info")
    void generatedTest() {
        step("Open https://www.mercadona.es/", () -> {
            step("// todo: just add selenium action");
        });

        step("Check main menu contains", () -> {
            step("// todo: just add selenium action");
        });

        step("Conócenos", () -> {
            step("// todo: just add selenium action");
        });

        step("Supermercados", () -> {
            step("// todo: just add selenium action");
        });

        step("Trabaja con nosotros", () -> {
            step("// todo: just add selenium action");
        });

        step("Atención al cliente", () -> {
            step("// todo: just add selenium action");
        });

        step("Check the field Codigo postal", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.mercadona.es/'", () ->
            open("https://www.mercadona.es/"));

        step("Page title should have text 'Mercadona'", () -> {
            String expectedTitle = "Mercadona";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.mercadona.es/'", () ->
            open("https://www.mercadona.es/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}